apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-vera
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vera
        context: sentinel-services
        version: v1
    spec:
      containers:
        -
          name: sentinel-vera
          image: docker.steventaylor.me/sentinel/services/vera/vera-x86_64:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: PORT
            value: "5000"
          - name: CONSUL
            value: consul
          - name: NEW_RELIC_NO_CONFIG_FILE
            value: "false"
          ports:
          -
            containerPort: 5000
            protocol: TCP