apiVersion: v1
kind: Service
metadata:
  name: sentinel-vera
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: vera
    context: sentinel-services
    version: v1
